name: Check KernelSU-Next tag update

on:
  schedule:
    - cron: '0 12 * * 1'
  workflow_dispatch:

jobs:
  update:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v3.5.3
        with:
          fetch-depth: 1

      - name: Check update
        run: |
          bash scripts/check-kernelsu-update.sh
